In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [7]:
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target


In [8]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [9]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler

iris = load_iris()
X = iris.data
y = iris.target

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)


print(X_scaled[:5])

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


In [10]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [11]:
X = df.drop('target', axis = 1)
Y = df['target']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size = 0.2, random_state = 42)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [14]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
model_KNN = KNeighborsClassifier()
model_KNN.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [16]:
y_pred = model_KNN.predict(X_test_scaled)

In [17]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [18]:
accuracy_score(y_pred, y_test)

1.0

In [19]:
# Export training data (scaled)
np.savetxt("X_train_scaled.csv", X_train_scaled, delimiter=",")
np.savetxt("y_train.csv", y_train, delimiter=",", fmt="%d")

# Export test data (scaled)
np.savetxt("X_test_scaled.csv", X_test_scaled, delimiter=",")
np.savetxt("y_test.csv", y_test, delimiter=",", fmt="%d")

# Export predictions
np.savetxt("y_pred.csv", y_pred, delimiter=",", fmt="%d")

print("All files exported!")

All files exported!


In [20]:
import numpy as np

# X fixed point conversion
X_train_fixed = (X_train_scaled * 255).round().astype(int)
X_test_fixed = (X_test_scaled * 255).round().astype(int)

# Export X
np.savetxt("X_train_fixed.csv", X_train_fixed, delimiter=",", fmt="%d")
np.savetxt("X_test_fixed.csv", X_test_fixed, delimiter=",", fmt="%d")

# Export Y (labels) - already integers, no fixed point needed
np.savetxt("y_train.csv", y_train, delimiter=",", fmt="%d")
np.savetxt("y_test.csv", y_test, delimiter=",", fmt="%d")

# Export predictions (golden reference for Verilog verification)
np.savetxt("y_pred.csv", y_pred, delimiter=",", fmt="%d")

print("X_train_fixed shape:", X_train_fixed.shape)
print("X_test_fixed shape:", X_test_fixed.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train_fixed shape: (120, 4)
X_test_fixed shape: (30, 4)
y_train shape: (120,)
y_test shape: (30,)


In [21]:
from google.colab import files

files.download("X_train_fixed.csv")
files.download("y_train.csv")
files.download("X_test_fixed.csv")
files.download("y_test.csv")
files.download("y_pred.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [22]:


# fixed point conversion
X_train_fixed = (X_train_scaled * 255).round().astype(int)
X_test_fixed = (X_test_scaled * 255).round().astype(int)

# print in a format easy to copy into Verilog
print("Training data (fixed point):")
for i, row in enumerate(X_train_fixed):
    print(f"  train_data[{i}] = {{8'd{row[0]}, 8'd{row[1]}, 8'd{row[2]}, 8'd{row[3]}}};  // label: {y_train.iloc[i]}")

Training data (fixed point):
  train_data[0] = {8'd22, 8'd170, 8'd0, 8'd11};  // label: 0
  train_data[1] = {8'd105, 8'd255, 8'd22, 8'd32};  // label: 0
  train_data[2] = {8'd180, 8'd117, 8'd152, 8'd138};  // label: 1
  train_data[3] = {8'd37, 8'd149, 8'd27, 8'd11};  // label: 0
  train_data[4] = {8'd8, 8'd128, 8'd13, 8'd11};  // label: 0
  train_data[5] = {8'd150, 8'd53, 8'd179, 8'd191};  // label: 2
  train_data[6] = {8'd158, 8'd128, 8'd157, 8'd149};  // label: 1
  train_data[7] = {8'd68, 8'd159, 8'd22, 8'd11};  // label: 0
  train_data[8] = {8'd52, 8'd170, 8'd18, 8'd11};  // label: 0
  train_data[9] = {8'd68, 8'd223, 8'd22, 8'd0};  // label: 0
  train_data[10] = {8'd112, 8'd74, 8'd183, 8'd191};  // label: 2
  train_data[11] = {8'd128, 8'd149, 8'd157, 8'd159};  // label: 1
  train_data[12] = {8'd180, 8'd117, 8'd166, 8'd149};  // label: 1
  train_data[13] = {8'd83, 8'd202, 8'd13, 8'd32};  // label: 0
  train_data[14] = {8'd83, 8'd181, 8'd22, 8'd11};  // label: 0
  train_data[15] = {8'